
services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ../.env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmine
    restart: always
    ports:
      - "8888:80"
    env_file:
      - ../.env
    volumes:
      - ./servers.json:/pgadmin4/servers.json
